
import type { Metadata } from "next";
import HeroSection from '@/components/HeroSection';
import Location from '@/components/Location';
import ServiceMenu from '@/components/ServiceMenu';
import HomeStats from '@/components/HomeStats';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <main>
      <HeroSection />
      <HomeStats/>
      <ServiceMenu />
      <Location/>
    </main>
  );
}